# Interpolated Local Vol

This notebook provides an object which can act as a local volatility function.

In [31]:
import numpy as np
import datetime
import scipy.interpolate as interp

import matplotlib.pyplot as plt
import seaborn.apionly as sns

plt.style.use('clean')

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [123]:
%%writefile interpolated_local_vol.py
import numpy as np
import scipy.interpolate as interp

class InterpolatedLocalVol:
    
    def __init__(self, point_estimates, dates, strikes, uses_dates=False):
        self.uses_dates = uses_dates
        self.point_estimates = point_estimates
        if uses_dates:
            self.raw_dates = np.array(dates)
            self.dates = np.array([d.toordinal() for d in dates])
        else:
            self.raw_dates = np.array(dates)
            self.dates = np.array(dates)
            
        self.strikes = np.array(strikes)
        self.f = interp.interp2d(self.strikes, self.dates, point_estimates, bounds_error=False)
    
    def __call__(self, raw_dates, strikes):
        if self.uses_dates:
            try:
                dates = np.array([d.toordinal() for d in raw_dates])
            except:
                dates = raw_dates.toordinal()
        else:
            dates = raw_dates
        
#         print(strikes)
#         print(dates)
        return self.f(strikes, dates)

Overwriting interpolated_local_vol.py


In [94]:
test_points = np.arange(12).reshape((3,4))
test_dates = [datetime.date(2017,1,1), 
              datetime.date(2017,2,1),
              datetime.date(2017,4,1)
             ]
test_strikes = [103, 105, 109, 110]

In [96]:
test_points

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
f = InterpolatedLocalVol(test_points, test_dates, test_strikes)

In [103]:
f.raw_dates

array([datetime.date(2017, 1, 1), datetime.date(2017, 2, 1),
       datetime.date(2017, 4, 1)], dtype=object)

In [104]:
f.strikes

array([103, 105, 109, 110])

In [105]:
f.point_estimates.shape

(3, 4)

In [106]:
f.point_estimates

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
f(datetime.date(2017,4,1), 109)

array([ 10.])

In [108]:
f(test_dates, test_strikes)

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [63]:
f(test_dates, 109)

array([ 6.,  7.,  8.])